### PR TITLE
Week 2 Assignment

### PR DESCRIPTION
**Pull request by WanjikuMac**
I have uploaded week 2 assignment for your review.
@zacck

### CODE REVIEW

**Review by zacck-zz — COMMENTED** [review]
can always link an issue to a pull request by referencing its like like #1

**Comment by zacck-zz** [comment]
@WanjikuMac  I can't see your code challenges from the book, this is good progress awesome work learning how to do pull requests

**Comment by WanjikuMac** [comment]
@zacck I've moved Chapter 2 exercises to week two branch.

**Comment by zacck-zz** [comment]
@WanjikuMac  it's called `backtick` notation and this branch looks good to go

**Review by zacck-zz — APPROVED** [review]
👍

**Pull request merged**
